{
    "code": "0000",
    "message": "",
    "data": {
        "spuID": 2000,
        "name": "SPU名称",
        "shortName": "SPU简称",
        "skus": [{
            "productID": "AJDLDSJL111",
            "skuTag": "SKU标签1",
            "productName": "商品名称",
            "productShortName": "商品简称",
            "associateTime": 1482736971241,
            "stock": 20,
            "channels": [{
                "channelID": "henan",
                "channelName": "河南",
                "vipPrice": 202.21,
                "mallPrice": 212.12,
                "subsidies": 12.21,
                "cost": 123.21,
                "status": 1
            }, {
                "channelID": "henan",
                "channelName": "河南",
                "vipPrice": 202.21,
                "mallPrice": 212.12,
                "subsidies": 12.21,
                "cost": 123.21,
                "status": 1
            }]
        }, {
            "productID": "AJDLDSJL111",
            "skuTag": "SKU标签1",
            "productName": "商品名称",
            "productShortName": "商品简称",
            "associateTime": 1482736971241,
            "stock": 20,
            "channels": [{
                "channelID": "henan",
                "channelName": "河南",
                "vipPrice": 202.21,
                "mallPrice": 212.12,
                "subsidies": 12.21,
                "cost": 123.21,
                "status": 1
            }, {
                "channelID": "henan",
                "channelName": "河南",
                "vipPrice": 202.21,
                "mallPrice": 212.12,
                "subsidies": 12.21,
                "cost": 123.21,
                "status": 1
            }]
        }, {
            "productID": "AJDLDSJL122",
            "skuTag": "SKU标签2",
            "productName": "商品名称",
            "productShortName": "商品简称",
            "associateTime": 1482736971241,
            "stock": 20,
            "channels": [{
                "channelID": "henan",
                "channelName": "河南",
                "vipPrice": 202.21,
                "mallPrice": 212.12,
                "subsidies": 12.21,
                "cost": 123.21,
                "status": 1
            }, {
                "channelID": "henan",
                "channelName": "河南",
                "vipPrice": 202.21,
                "mallPrice": 212.12,
                "subsidies": 12.21,
                "cost": 123.21,
                "status": 1
            }]
        }, {
            "productID": "AJDLDSJL123",
            "skuTag": "SKU标签3",
            "productName": "商品名称",
            "productShortName": "商品简称",
            "associateTime": 1482736971241,
            "stock": 20,
            "channels": [{
                "channelID": "henan",
                "channelName": "河南",
                "vipPrice": 202.21,
                "mallPrice": 212.12,
                "subsidies": 12.21,
                "cost": 123.21,
                "status": 1
            }, {
                "channelID": "henan",
                "channelName": "河南",
                "vipPrice": 202.21,
                "mallPrice": 212.12,
                "subsidies": 12.21,
                "cost": 123.21,
                "status": 1
            }]
        }]
    }
}
