{
    "code": "0000",
    "message": "分类查询成功",
    "data": {
        "total": 30,
        "pageNumber": 11,
        "pageSize": 20,
        "spus": [{
            "spuID": 21111,
            "name": "这个是名字",
            "shortName": "简称",
            "updateTime": 1482465502993,
            "skus": [{
                "productID": "1212ADKLDKDL21",
                "skuTag": "白色M码"
            }, {
                "productID": "1212ADKLD21212",
                "skuTag": "红色L码"
            }, {
                "productID": "1212ADKLDKDL311",
                "skuTag": "红色M码"
            }, {
                "productID": "1212ADKLDKDL212",
                "skuTag": "白色M码"
            }, {
                "productID": "1212ADKLD212123",
                "skuTag": "红色L码"
            }, {
                "productID": "1212ADKLDKDL314",
                "skuTag": "红色M码"
            }, {
                "productID": "1212ADKLDKDL215",
                "skuTag": "白色M码"
            }, {
                "productID": "1212ADKLD212126",
                "skuTag": "红色L码"
            }, {
                "productID": "1212ADKLDKDL315",
                "skuTag": "红色M码"
            }]
        }, {
            "spuID": 21111,
            "name": "这个是名字",
            "shortName": "简称",
            "updateTime": 1482465502993,
            "skus": [{
                "productID": "1212ADKLDKDL21",
                "skuTag": "白色M码"
            }, {
                "productID": "1212ADKLD21212",
                "skuTag": "红色L码"
            }, {
                "productID": "1212ADKLDKDL31",
                "skuTag": "红色M码"
            }, {
                "productID": "1212ADKLDKDL51",
                "skuTag": "白色M码"
            }, {
                "productID": "1212ADKLD21262",
                "skuTag": "红色L码"
            }, {
                "productID": "1212ADKLDKDL71",
                "skuTag": "红色M码"
            }]
        }, {
            "spuID": 21121,
            "name": "这个是名字二",
            "shortName": "简称二",
            "updateTime": 1482465502993,
            "skus": [{
                "productID": "1212ADKLDKDL21",
                "skuTag": "白色M码"
            }, {
                "productID": "1212ADKLD21212",
                "skuTag": "红色L码"
            }, {
                "productID": "1212ADKLDKDL33",
                "skuTag": "红色M码"
            }, {
                "productID": "1212ADKLDKDL24",
                "skuTag": "白色M码"
            }, {
                "productID": "1212ADKLD21215",
                "skuTag": "红色L码"
            }, {
                "productID": "1212ADKLDKDL36",
                "skuTag": "红色M码"
            }]
        }]
    }
}
