{
    "code": "0000",
    "message": "",
    "data": {
        "total": 120,
        "offset": 50,
        "limit": 50,
        "productList": [{
            "orderId": "orderId",
            "suborderId": "suborderId",
            "orderStatus": 1,
            "merchantName": "供应商简称",
            "channel": "demo",
            "channelName": "银行渠道",
            "createTime": 1471253404736,
            "payTime": 1471253404736,
            "productId": "商品编号",
            "refundStatus": 2,
            "confirmState": 200,
            "productName": "商品简称"
        }, {
            "orderId": "orderId",
            "suborderId": "suborderId",
            "orderStatus": 1,
            "merchantName": "供应商简称",
            "channel": "demo",
            "channelName": "银行渠道",
            "createTime": 1471253404736,
            "payTime": 1471253404736,
            "productId": "商品编号",
            "refundStatus": 2,
            "confirmState": 200,
            "productName": "商品简称"
        }, {
            "orderId": "orderId",
            "suborderId": "suborderId",
            "orderStatus": 1,
            "merchantName": "供应商简称",
            "channel": "demo",
            "channelName": "银行渠道",
            "createTime": 1471253404736,
            "payTime": 1471253404736,
            "productId": "商品编号",
            "refundStatus": 2,
            "confirmState": 200,
            "productName": "商品简称"
        }, {
            "orderId": "orderId",
            "suborderId": "suborderId",
            "orderStatus": 1,
            "merchantName": "供应商简称",
            "channel": "demo",
            "channelName": "银行渠道",
            "createTime": 1471253404736,
            "payTime": 1471253404736,
            "productId": "商品编号",
            "refundStatus": 2,
            "confirmState": 200,
            "productName": "商品简称"
        }]
    }
}
