{
    "code": "0000",
    "message": "很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长错误很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长",
    "data": {
        "orderInfo": {
            "orderId": "123456789012345678901234",
            "memberCode": "12345678901234567890",
            "channel":  "bank",
            "channelName": "赤峰嵩山农商行",
            "createTime": 1471263659531,
            "payTime": 1471263659531,
            "totalPrice": 1000,
            "orderStatus": 122,
            "cashAmount": 200,
            "billNo": "61212171620229,61212171547228",
            "pointType": 1,
            "pointAmount": 3000,
            "pointNo": "3435324543,234534534543543,34534532452345",
            "redPacketActiveID": "xinhua-NVB-sdf1233",
            "redPacketDenomination": 12.098,
            "suborders": [{
                "suborderId": "123456789012345678901234",
                "merchantName": "供应商简称1",
                "products": [{
                    "productId": "123456789012345678901234",
                    "productName": "商品简称22商品简称22商品简称22商品简称商品简称",
                    "deliveryTime": 1471263659531,
                    "productType": "1",
                    "category1": 1,
                    "category1Name": "二级",
                    "category2": 2,
                    "category2Name": "三级分类",
                    "category3": 3,
                    "category3Name": "三级分类",
                    "vipUnitPrice": 2001,
                    "vipQuantity": 2000,
                    "unitPrice": 2111,
                    "quantity": 200,
                    "productAmount": 112,
                    "refundStatus": 100,
                    "confirmState": 204
                }, {
                    "productId": "商品编号",
                    "productName": "商品简称",
                    "deliveryTime": "1111",
                    "productType": "1",
                    "category1": 1,
                    "category1Name": "一级",
                    "category2": 2,
                    "category2Name": "二级分类",
                    "category3": 3,
                    "category3Name": "三级分类",
                    "vipUnitPrice": 2001,
                    "vipQuantity": 20000,
                    "unitPrice": 211111,
                    "quantity": 20,
                    "productAmount": 112,
                    "refundStatus": 201,
                    "confirmState": 1
                }]
            }, {
                "suborderId": "0111",
                "merchantName": "供应商简称",
                "products": [{
                    "productId": "商品编号",
                    "productName": "商品简称",
                    "deliveryTime": "1111",
                    "productType": "1",
                    "category1": 1,
                    "category1Name": "一级",
                    "category2": 2,
                    "category2Name": "二级分类二级分类二级分",
                    "category3": 3,
                    "category3Name": "三级分类",
                    "vipUnitPrice": 2001,
                    "vipQuantity": 20000,
                    "unitPrice": 211111,
                    "quantity": 20,
                    "productAmount": 112,
                    "refundStatus": 3,
                    "confirmState": 200
                }]
            },{
                "suborderId": "0111",
                "merchantName": "供应商简称",
                "products": [{
                    "productId": "商品编号",
                    "productName": "商品简称",
                    "deliveryTime": "1111",
                    "productType": "1",
                    "category1": 1,
                    "category1Name": "一级",
                    "category2": 2,
                    "category2Name": "二级分类",
                    "category3": 3,
                    "category3Name": "三级分类",
                    "vipUnitPrice": 2001,
                    "vipQuantity": 20000,
                    "unitPrice": 211111,
                    "quantity": 20,
                    "productAmount": 112,
                    "refundStatus": 3,
                    "confirmState": 1
                }]
            }]
        }
    }
}
