{
    "code": "0000",
    "message": "查询成功",
    "data": {
        "channelList": [{
            "channel": "chongqing",
            "channelName": "重庆"
        }, {
            "remark": "",
            "channel": "jilin",
            "channelName": "吉林"
        }, {
            "remark": "",
            "channel": "taizhou",
            "channelName": "台州"
        }, {
            "channel": "weifang",
            "channelName": "潍坊农信"
        }, {
            "channel": "wujiang",
            "channelName": "吴江农信"
        }, {
            "channel": "etuoke",
            "channelName": "鄂托克农商行"
        }, {
            "channel": "xinghua",
            "channelName": "兴化农村商业银行"
        }, {
            "channel": "ningcheng",
            "channelName": "宁城农商行"
        }, {
            "channel": "kalaqinqi",
            "channelName": "喀喇沁旗农信"
        }, {
            "channel": "shenyang",
            "channelName": "沈阳农商银行"
        }, {
            "channel": "songshan",
            "channelName": "赤峰松山农商行"
        }, {
            "channel": "leshan",
            "channelName": "乐山农商行"
        }, {
            "channel": "froadmall",
            "channelName": "上海方付通商务服务有限公司"
        }, {
            "channel": "shangqiu",
            "channelName": "商丘华商农商行"
        }]
    }
}
